// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzydg66Wq0kWrZaP4XJYe0uhLRDWbNsU',
    appId: '1:918686354616:web:9af21a310587d65d9a784d',
    messagingSenderId: '918686354616',
    projectId: 'btd6-wiki',
    authDomain: 'btd6-wiki.firebaseapp.com',
    storageBucket: 'btd6-wiki.appspot.com',
    measurementId: 'G-K5GRWBPP70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvhQpeZlR7jjUPzNBFs9GQLuDOU2EuguQ',
    appId: '1:918686354616:android:517981078d775b709a784d',
    messagingSenderId: '918686354616',
    projectId: 'btd6-wiki',
    storageBucket: 'btd6-wiki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4E-D2uyGYDAYHx1dTJ-GjW4bNMHlaVTM',
    appId: '1:918686354616:ios:ce6e9a83cdb3074e9a784d',
    messagingSenderId: '918686354616',
    projectId: 'btd6-wiki',
    storageBucket: 'btd6-wiki.appspot.com',
    iosBundleId: 'com.example.btd6wiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4E-D2uyGYDAYHx1dTJ-GjW4bNMHlaVTM',
    appId: '1:918686354616:ios:ce6e9a83cdb3074e9a784d',
    messagingSenderId: '918686354616',
    projectId: 'btd6-wiki',
    storageBucket: 'btd6-wiki.appspot.com',
    iosBundleId: 'com.example.btd6wiki',
  );
}
